// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tilith.Core.Data;

#nullable disable

namespace Tilith.Core.Data.Migrations
{
    [DbContext(typeof(TilithDbContext))]
    partial class TilithDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-rc.2.25502.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tilith.Core.Entities.User", b =>
                {
                    b.Property<decimal>("DiscordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint");

                    b.Property<int>("Gems")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastDailyClaimUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DiscordId");

                    b.HasIndex("Experience");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
